version: '3.5'
services:
  postgres:
    container_name: postgres_text_db_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: text_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - .:/docker-entrypoint-initdb.d
    command: postgres -c 'max_connections=1000'
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      retries: 3
      start_period: 5s
    networks:
      speed_typing:
    restart: unless-stopped

  speed_typing_text_service:
    container_name: speed_typing_text_service_container
    image: ghcr.io/ttodoshi/speed-typing-text-service:latest
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 8080
      PROFILE: "dev"# dev, prod
      LOG_LEVEL: "debug"#trace, debug, info, warn, error
      DB_URL: "host=postgres user=postgres password=pass dbname=text_db port=5432 sslmode=disable"
    networks:
      speed_typing:

#  mongo:
#    image: mongo
#    container_name: mongo_container
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=pass
#    volumes:
#      - mongo:/data/db
#    ports:
#      - '27017:27017'
#    networks:
#      speed_typing:
#    restart: unless-stopped

networks:
  speed_typing:
    driver: bridge

volumes:
  postgres:
#  mongo: