version: '3.5'
services:
  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -dev -client 0.0.0.0 -ui"
    environment:
      CONSUL_BIND_INTERFACE: eth0
    networks:
      - speed-typing
    restart: always
  speed-typing-gateway-service:
    container_name: speed-typing-text-gateway-container
    image: ghcr.io/ttodoshi/speed-typing-gateway-service:latest
    ports:
      - "8443:8443"
    depends_on:
      - consul
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
    networks:
      - speed-typing

  postgres-text-db:
    container_name: postgres-text-db-container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: text_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - .:/docker-entrypoint-initdb.d
    command: postgres -c 'max_connections=1000'
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      retries: 3
      start_period: 5s
    networks:
      - speed-typing
    restart: unless-stopped

  speed-typing-text-service:
    container_name: speed-typing-text-service-container
    image: ghcr.io/ttodoshi/speed-typing-text-service:latest
    ports:
      - "8080:8080"
    depends_on:
      postgres-text-db:
        condition: service_healthy
    environment:
      PORT: 8080
      PROFILE: "dev"# dev, prod
      LOG_LEVEL: "debug"#trace, debug, info, warn, error
      DB_URL: "host=postgres-text-db user=postgres password=pass dbname=text_db port=5432 sslmode=disable"
      CONSUL_HOST: "consul:8500"
      CONSUL_SERVICE_NAME: "text-service"
      CONSUL_SERVICE_ADDRESS: "speed-typing-text-service"
    networks:
      - speed-typing

  mongo:
    image: mongo
    container_name: mongo-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      retries: 3
      start_period: 5s
    networks:
      speed-typing:
    restart: unless-stopped

  speed-typing-auth-service:
    container_name: speed-typing-auth-service-container
    image: ghcr.io/ttodoshi/speed-typing-auth-service:latest
    ports:
      - "8090:8090"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      ACCESS_TOKEN_EXP_SECONDS: "300s"
      REFRESH_TOKEN_EXP_SECONDS: "1209600s"
      COOKIE_HOST: "localhost"
      SECRET_KEY: "Popa"
      PORT: 8090
      PROFILE: "dev"# dev, prod
      LOG_LEVEL: "debug"#trace, debug, info, warn, error
      DB_URL: "mongodb://admin:pass@mongo:27017"
      CONSUL_HOST: "consul:8500"
      CONSUL_SERVICE_NAME: "auth-service"
      CONSUL_SERVICE_ADDRESS: "speed-typing-auth-service"
    networks:
      - speed-typing

networks:
  speed-typing:
    driver: bridge

volumes:
  postgres:
  mongo:
