version: '3.5'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DATABASE: text_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    command: postgres -c 'max_connections=1000'
    ports:
      - "5432:5432"
    networks:
      speed_typing:
    restart: unless-stopped

#  mongo:
#    image: mongo
#    container_name: mongo_container
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=pass
#    volumes:
#      - mongo:/data/db
#    ports:
#      - '27017:27017'
#    networks:
#      speed_typing:
#    restart: unless-stopped

networks:
  speed_typing:
    driver: bridge

volumes:
  postgres:
#  mongo: